In [ ]:
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
s = "This is very good movie"

print(word_tokenize(s))

['This', 'is', 'very', 'good', 'movie']

In [ ]:
lens = [w for w in s.split()]
print(lens)

['This', 'is', 'very', 'good', 'movie']

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
from nltk.corpus import stopwords
words = stopwords.words('english')

print(words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [ ]:
print(np.shape(words))

(179,)

In [ ]:
stop = np.array(words)
print(stop.shape)

(179,)

In [ ]:
# lengths = [w for w in len if w not in stop]
# print(lengths)

In [ ]:
data = ["this is a good movie", "what a bad movie"]
data = np.array(data)

# data = data.apply(lambda x: ' '.join[w for w in x.split() if not in stop])

In [ ]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [ ]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
stemmed = [ps.stem(w) for w in lens]

print(stemmed)

['thi', 'is', 'veri', 'good', 'movi']

In [ ]:
PorterStemmer?

In [ ]:
train = pd.read_csv('https://raw.githubusercontent.com/dD2405/Twitter_Sentiment_Analysis/master/train.csv')

train.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [ ]:
train.describe()

                 id         label
count  31962.000000  31962.000000
mean   15981.500000      0.070146
std     9226.778988      0.255397
min        1.000000      0.000000
25%     7991.250000      0.000000
50%    15981.500000      0.000000
75%    23971.750000      0.000000
max    31962.000000      1.000000

In [ ]:
test = pd.read_csv('https://raw.githubusercontent.com/dD2405/Twitter_Sentiment_Analysis/master/test.csv')
test.head()

      id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

@user, punctuations, stopwords are unnecessary.

In [ ]:
cleaning = train['tweet'].values

In [ ]:
cleaning

array([' @user when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run',
       "@user @user thanks for #lyft credit i can't use cause they don't offer wheelchair vans in pdx.    #disapointed #getthanked",
       '  bihday your majesty', ...,
       'listening to sad songs on a monday morning otw to work is sad  ',
       '@user #sikh #temple vandalised in in #calgary, #wso condemns  act  ',
       'thank you @user for you follow  '], dtype=object)

In [ ]:
for sen in cleaning:
  lensen = [w for w in sen.split()]

In [ ]:
import re

In [ ]:
def remove_pattern(pattern, text):
  occur = re.findall(pattern, text)
  for i in occur:
    text = re.sub(i, '', text)

  return text

In [ ]:
train['new_tweet'] = [remove_pattern("@[\w]*", sen) for sen in train['tweet']]

train.head()

   id  ...                                          new_tweet
0   1  ...    when a father is dysfunctional and is so sel...
1   2  ...    thanks for #lyft credit i can't use cause th...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide: society now    #motivation

[5 rows x 4 columns]

In [ ]:
train['new_tweet'] = train['new_tweet'].str.replace("[^a-zA-Z#]", " ")

train.head()

   id  ...                                          new_tweet
0   1  ...    when a father is dysfunctional and is so sel...
1   2  ...    thanks for #lyft credit i can t use cause th...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide  society now    #motivation

[5 rows x 4 columns]

In [ ]:
train['new_tweet'] = train['new_tweet'].apply(lambda x: x.split())

train.head()

   id  ...                                          new_tweet
0   1  ...  [when, a, father, is, dysfunctional, and, is, ...
1   2  ...  [thanks, for, #lyft, credit, i, can, t, use, c...
2   3  ...                            [bihday, your, majesty]
3   4  ...  [#model, i, love, u, take, with, u, all, the, ...
4   5  ...            [factsguide, society, now, #motivation]

[5 rows x 4 columns]

In [ ]:
train['new_tweet'] = train['new_tweet'].apply(lambda x: [w for w in x if w not in stop])

train.head()

   id  ...                                          new_tweet
0   1  ...  [father, dysfunctional, selfish, drags, kids, ...
1   2  ...  [thanks, #lyft, credit, use, cause, offer, whe...
2   3  ...                                  [bihday, majesty]
3   4  ...               [#model, love, u, take, u, time, ur]
4   5  ...                 [factsguide, society, #motivation]

[5 rows x 4 columns]

In [ ]:
train['new_tweet'] = train['new_tweet'].apply(lambda x: [ps.stem(w) for w in x])
train['new_tweet'] = train['new_tweet'].apply( lambda x: ' '.join(x))

train.head()

   id  ...                                          new_tweet
0   1  ...     father dysfunct selfish drag kid dysfunct #run
1   2  ...  thank #lyft credit use caus offer wheelchair v...
2   3  ...                                     bihday majesti
3   4  ...                       #model love u take u time ur
4   5  ...                           factsguid societi #motiv

[5 rows x 4 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vec = CountVectorizer?

In [ ]:
vectorize = CountVectorizer(max_df = 0.8, min_df = 2, max_features=1000, stop_words='english')
f_data = vectorize.fit_transform(train['new_tweet'])

pdf_data = pd.DataFrame(f_data.todense())

pdf_data

       0    1    2    3    4    5    6    ...  993  994  995  996  997  998  999
0        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
31957    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31958    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31959    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
31960    0    0    0    0    1    0    0  ...    0    0    0    0    0    0    0
31961    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[31962 rows x 1000 columns]

In [ ]:
pdf_data.describe()

                0             1    ...           998           999
count  31962.000000  31962.000000  ...  31962.000000  31962.000000
mean       0.002284      0.001783  ...      0.002503      0.001377
std        0.048388      0.042193  ...      0.051205      0.041836
min        0.000000      0.000000  ...      0.000000      0.000000
25%        0.000000      0.000000  ...      0.000000      0.000000
50%        0.000000      0.000000  ...      0.000000      0.000000
75%        0.000000      0.000000  ...      0.000000      0.000000
max        2.000000      1.000000  ...      2.000000      4.000000

[8 rows x 1000 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(pdf_data, train['label'], test_size=0.30, random_state=0)

In [ ]:
np.unique(Y_train, return_counts = True)

(array([0, 1]), array([20766,  1607]))

In [ ]:
np.unique(Y_test, return_counts = True)

(array([0, 1]), array([8954,  635]))

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(solver = 'lbfgs')

lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
Y_pred_lr = lr.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(Y_pred_lr,Y_test)*100

In [ ]:
print(accuracy)

94.92126394827406

In [ ]:
np.unique(Y_pred_lr, return_counts = True)

(array([0, 1]), array([9251,  338]))

In [ ]:
from sklearn.metrics import f1_score

acc = f1_score(Y_pred_lr, Y_test)
print(acc)

0.49948612538540593

In [ ]:
8954+635

9589

In [ ]:
8954/9589

0.9337782876212327

In [ ]:
from sklearn import svm

sv = svm.SVC(kernel='linear')

sv.fit(X_train, Y_train)
# 2 m 34 s

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
Y_pred_svm = sv.predict(X_test)

In [ ]:
accuracy_svm = accuracy_score(Y_pred_svm, Y_test)*100

In [ ]:
print(accuracy)

94.99426426113254

In [ ]:
f1_svm = f1_score(Y_pred_svm, Y_test)
print(f1_svm)

0.5041322314049587

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec2 = TfidfVectorizer()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec2 = TfidfVectorizer(max_df = 0.8, min_df = 2, max_features=1000, stop_words='english')

f_data2 = vec2.fit_transform(train['new_tweet'])

pdf_data2 = pd.DataFrame(f_data2.todense())

pdf_data2

       0    1    2    3    4    5    6    ...  993  994  995  996  997  998  999
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
31957  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31958  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31959  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31960  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
31961  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[31962 rows x 1000 columns]

In [ ]:
X_train2, X_test2, Y_train2, Y_test2 = train_test_split(pd.DataFrame((vec2.fit_transform(train['new_tweet'])).todense()), train['label'], test_size=0.30, random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression

lr2 = LogisticRegression(solver = 'lbfgs')

lr2.fit(X_train2, Y_train2)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
Y_pred_lr2 = lr2.predict(X_test2)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy2 = accuracy_score(Y_pred_lr2,Y_test2)*100

In [ ]:
print(accuracy2)

95.07769319011368

In [ ]:
np.unique(Y_pred_lr2, return_counts = True)

(array([0, 1]), array([9310,  279]))

In [ ]:
from sklearn.metrics import f1_score

acc2 = f1_score(Y_pred_lr2, Y_test2)
print(acc2)

0.4835886214442013

In [ ]:
from sklearn import svm

sv2 = svm.SVC(kernel='linear')

sv2.fit(X_train2, Y_train2)
# 2 m 3 s

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
Y_pred_svm2 = sv2.predict(X_test2)

In [ ]:
accuracy_svm2 = accuracy_score(Y_pred_svm2, Y_test2)*100

In [ ]:
print(accuracy_svm2)

95.09855042235895

In [ ]:
f1_svm2 = f1_score(Y_pred_svm2, Y_test2)
print(f1_svm2)

0.49678800856531047